services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm/8.1
      dockerfile: Dockerfile
      args:
        WWW_DATA_UID: ${DOCKER_USER_UID}
        WWW_DATA_GID: ${DOCKER_USER_GID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/app
    environment:
      APP_ENV: "dev"
      PHP_IDE_CONFIG: "serverName=rollun-logger"
      APP_DEBUG: "true"
      LOGS_REDIS_HOST: "host.docker.internal"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  csfixer:
    image: ghcr.io/php-cs-fixer/php-cs-fixer:3.75-php8.0
    volumes:
      - ./:/code