version: "3.8"

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
      - /home/work/Work/.ssh:/root/.ssh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_ENV: test
      PHP_IDE_CONFIG: "serverName=rollun-logger"
      APP_DEBUG: "true"
      LOGS_REDIS_HOST: "host.docker.internal"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379