name: PHP Composer

on:
  push:
    branches: [ 6.x ]
  pull_request:
    branches: [ 6.x ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        extensions: json, zip, mysqli, pdo_mysql
        tools: composer:v1
  
    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run test suite
      run: |
        cp test/.env .env
        composer run-script test
